### ISSUE TITLE
Question in sample file

### ISSUE THREAD

**Issue by lishuhanin** [cpouchon/REFMAKER#2]
Hello charles,
I'm interesting in your  soft REFMAKER.It can get the nuclear loci from low-coverage libraries.I want share it in my group meeting. But i try it in assemble step,I find i don't know how to correctly make Sample file.I made a  samples.txt,like this 
![image](https://github.com/cpouchon/REFMAKER/assets/139117432/5f2b36e9-6989-45f6-9041-9dae65e6b002)
then ran ./refmaker -m assembly -o sample -p parameter.txt,appeared next situation

> [INFO]: spades assembly run
 -2  --cov-cutoff auto -o res_refmaker/assembly/spades/Ajuga_decumbens_167911_AJ19 -t 4 -m 10 -k 55
SPAdes genome assembler v3.15.5

> Usage: spades.py [options] -o <output_dir>
spades.py: error: argument -2: expected 1 argument
 -2  --cov-cutoff auto -o res_refmaker/assembly/spades//mnt2/Lish/second_uncomplement_AJ/Ajuga_decumbens_167911/Ajuga_decumbens_167911_AJ19_1.fq.gz -t 4 -m 10     -k 55
SPAdes genome assembler v3.15.5

> Usage: spades.py [options] -o <output_dir>
spades.py: error: argument -2: expected 1 argument
[INFO]: time ellapsed for assembly step: 0:0:1 (hh:mm:ss)
[STATUS]: done

I don't know why appear this question.Could you tell me how to solution this question?I'm looking forward to your reply.

Thank you for your time,

Li shuhan

**Comment by lishuhanin** [comment]
I have modify the sample.txt,like this
![image](https://github.com/cpouchon/REFMAKER/assets/139117432/47970166-66c0-47e7-8568-96f541166a56)
Remenber choose Linux in the top tool! Now it is working.
Thank you for your REFMAKER,i wish you will get more achievement in future.
Best wishes

**Comment by cpouchon** [comment]
Hi Li, 
thank your for comment, I had also some issues about the format between Mac/Linux. 
Let me know if it is running properly. 
Best regards, 
Charles
